# Generated by Django 4.2 on 2023-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='ip',
            field=models.CharField(default=102, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadchannel',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
